"""
proposed_metric_matrix.py
==========================
Reads all 50 Supreme Court verdict .txt files across 3 document types,
scores each document using the GMM-trained vocabulary model to compute:
  - Layman Score %        (LAYMAN cluster from GMM)
  - Budding Lawyer Score% (STUDENT cluster from GMM)
  - Advocate Score %      (PROFESSIONAL cluster from GMM)
  - Proposed Metric Avg   = (Layman + BuddingLawyer + Advocate) / 3

This is your LockNKey system's core proposed metric — validated using
the GMM model you trained on the Supreme Court corpus.

Run:
    python proposed_metric_matrix.py

Requires:
    output/layman_vocabulary.csv       (generated by run_pipeline.py)
    output/student_vocabulary.csv
    output/professional_vocabulary.csv

Output:
    output/proposed_metric_matrix.csv   (Sheet 1 data — Proposed Metric Avg)
    output/audience_matrix.csv          (Sheet 2 data — Layman, BL, Advocate %)
"""

import os
import re
import csv
import pandas as pd

# ── PATHS (auto-detects your folder structure) ─────────────────────
def find_folder(candidates):
    for p in candidates:
        if os.path.isdir(p):
            return p
    raise FileNotFoundError(f"Could not find any of: {candidates}")

JUDG_DIR = find_folder([
    os.path.join("data", "IN-Ext_judgement"),
    "IN-Ext_judgement",
])
GT_DIR = find_folder([
    os.path.join("data", "summary", "A1_Ground truth"),
    os.path.join("data", "A1_Ground truth"),
    os.path.join("summary", "A1_Ground truth"),
    "A1_Ground truth",
])
LK_DIR = find_folder([
    os.path.join("data", "summary", "A2_LocknKey"),
    os.path.join("data", "A2_LocknKey"),
    os.path.join("summary", "A2_LocknKey"),
    "A2_LocknKey",
])
VOCAB_DIR = "output"
OUT_PROP  = os.path.join("output", "proposed_metric_matrix.csv")
OUT_AUD   = os.path.join("output", "audience_matrix.csv")
os.makedirs("output", exist_ok=True)

print(f"  JUDG folder : {JUDG_DIR}")
print(f"  GT folder   : {GT_DIR}")
print(f"  LK folder   : {LK_DIR}\n")

# ── LOAD GMM VOCABULARY ────────────────────────────────────────────
print("Loading GMM-trained vocabulary...")
layman_vocab  = set(pd.read_csv(os.path.join(VOCAB_DIR, "layman_vocabulary.csv"))["word"].str.lower())
student_vocab = set(pd.read_csv(os.path.join(VOCAB_DIR, "student_vocabulary.csv"))["word"].str.lower())
prof_vocab    = set(pd.read_csv(os.path.join(VOCAB_DIR, "professional_vocabulary.csv"))["word"].str.lower())

print(f"  LAYMAN      : {len(layman_vocab)} words")
print(f"  STUDENT     : {len(student_vocab)} words  → Budding Lawyer")
print(f"  PROFESSIONAL: {len(prof_vocab)} words  → Advocate")

# ── GMM SCORER ─────────────────────────────────────────────────────
def gmm_scores(text):
    """
    For every word token in the document:
      - Match it against GMM-classified vocabulary (layman / student / professional)
      - Compute % share of each audience cluster among all matched tokens

    Returns:
      layman_pct   → Layman Score %
      student_pct  → Budding Lawyer Score %
      prof_pct     → Advocate Score %
      proposed_avg → (layman + student + prof) / 3
    """
    tokens    = re.findall(r"[a-z]{3,}", text.lower())
    lay_c     = sum(1 for w in tokens if w in layman_vocab)
    stu_c     = sum(1 for w in tokens if w in student_vocab)
    pro_c     = sum(1 for w in tokens if w in prof_vocab)
    matched   = max(1, lay_c + stu_c + pro_c)

    lay_pct   = round(100 * lay_c / matched, 4)
    stu_pct   = round(100 * stu_c / matched, 4)
    pro_pct   = round(100 * pro_c / matched, 4)
    prop_avg  = round((lay_pct + stu_pct + pro_pct) / 3, 4)

    return lay_pct, stu_pct, pro_pct, prop_avg

# ── COMPUTE ────────────────────────────────────────────────────────
case_files = sorted(os.listdir(JUDG_DIR))
prop_rows  = []   # Sheet 1 — Proposed Metric Avg per doc type
aud_rows   = []   # Sheet 2 — Layman, BL, Advocate per doc type

print(f"\nComputing GMM scores for {len(case_files)} cases...\n")
print(f"{'Case':<6} {'Case ID':<15} {'Doc Type':<22} {'Layman%':>9} {'BL%':>9} {'Adv%':>9} {'Prop Avg':>10}")
print("-" * 85)

DOC_TYPES = [
    ("Original Judgement",  JUDG_DIR),
    ("Ground Truth Summary", GT_DIR),
    ("LockNKey Summary",     LK_DIR),
]

for i, fname in enumerate(case_files):
    case_num = i + 1
    case_id  = fname.replace(".txt", "")

    scores_per_doc = {}
    for doc_label, folder in DOC_TYPES:
        text = open(os.path.join(folder, fname), encoding="utf-8", errors="ignore").read()
        lay, stu, pro, prop = gmm_scores(text)
        scores_per_doc[doc_label] = (lay, stu, pro, prop)

        aud_rows.append({
            "case_num":          case_num,
            "case_id":           case_id,
            "doc_type":          doc_label,
            "layman_score_pct":  lay,
            "budding_lawyer_pct": stu,
            "advocate_pct":      pro,
            "proposed_avg":      prop,
        })

        print(f"  {case_num:<4} {case_id:<15} {doc_label:<22} {lay:>9.4f} {stu:>9.4f} {pro:>9.4f} {prop:>10.4f}")

    oj_prop  = scores_per_doc["Original Judgement"][3]
    gt_prop  = scores_per_doc["Ground Truth Summary"][3]
    lk_prop  = scores_per_doc["LockNKey Summary"][3]

    prop_rows.append({
        "case_num":                    case_num,
        "case_id":                     case_id,
        "proposed_avg_orig_judgement": oj_prop,
        "proposed_avg_ground_truth":   gt_prop,
        "proposed_avg_locknkey":       lk_prop,
    })

    print()

# ── SAVE CSVs ──────────────────────────────────────────────────────
with open(OUT_PROP, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=list(prop_rows[0].keys()))
    writer.writeheader()
    writer.writerows(prop_rows)

with open(OUT_AUD, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=list(aud_rows[0].keys()))
    writer.writeheader()
    writer.writerows(aud_rows)

print(f"✅ Saved: {OUT_PROP}   ({len(prop_rows)} rows — Proposed Metric Avg)")
print(f"✅ Saved: {OUT_AUD}  ({len(aud_rows)} rows — Audience Scores)")